### ISSUE TITLE
Can we used this on iOs push notification?

### ISSUE THREAD

**Issue by noprobz09** [matriphe/gcm#2]
Hello,

Can we used this on iOs push notification? how can we configure for iOs using the .pem? 

Thank you! :)

**Comment by matriphe** [comment]
No, it can not. GCM stand for Google Cloud Message that use Google Clod Message protocol. If you're using iOS, please refer to APN (Apple Push Notification) service https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html
